name: Update EC2 SG for GitHub Actions IPs (Split Across 3 SGs)

on:
  workflow_dispatch:

jobs:
  update-sg:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq unzip curl

      - name: Upgrade AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo ln -sf /usr/local/bin/aws /usr/bin/aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update 3 security groups with GitHub Actions IPs
        env:
          SG_1: ${{ secrets.SG_ID_1 }}
          SG_2: ${{ secrets.SG_ID_2 }}
          SG_3: ${{ secrets.SG_ID_3 }}
        run: |
          echo "📦 Fetching GitHub Actions IPs..."
          IP_LIST=($(curl -s https://api.github.com/meta | jq -r '.actions[]'))

          echo "🧹 Revoking old rules from all SGs..."
          for SG in $SG_1 $SG_2 $SG_3; do
            EXISTING=$(/usr/local/bin/aws ec2 describe-security-groups \
              --group-ids "$SG" \
              --query "SecurityGroups[0].IpPermissions[?ToPort==\`22\`].IpRanges[?Description==\`GitHub Actions\`].CidrIp" \
              --output text)
            for CIDR in $EXISTING; do
              echo "➡️ Revoking $CIDR from $SG..."
              /usr/local/bin/aws ec2 revoke-security-group-ingress \
                --group-id "$SG" \
                --protocol tcp \
                --port 22 \
                --cidr "$CIDR"
            done
          done

          echo "➕ Distributing new IPs across 3 SGs..."
          COUNT=0
          for CIDR in "${IP_LIST[@]}"; do
            if (( COUNT < 60 )); then
              SG=$SG_1
            elif (( COUNT < 120 )); then
              SG=$SG_2
            else
              SG=$SG_3
            fi

            echo "➡️ Adding $CIDR to $SG..."
            /usr/local/bin/aws ec2 authorize-security-group-ingress \
              --group-id "$SG" \
              --protocol tcp \
              --port 22 \
              --cidr "$CIDR"

            COUNT=$((COUNT + 1))
          done

          echo "✅ All GitHub Actions IPs distributed across 3 security groups."
